test(http2): add mem channel test
n0-computer/quic-rpc pull request #23
Opened 2022-12-21 09:01 UTC by rklaehn

This also serves as an example how to use the fully custom constructors for http2 server and client.

2022-12-21 09:02 UTC, rklaehn commented on src/transport/http2.rs
> +    pub fn new_with_connector<C>(connector: C, uri: Uri, config: Arc<ChannelConfig>) -> Self
Just reformatting to put the where clause outside

2022-12-21 11:21 UTC, flub approved these changes

2022-12-21 15:53 UTC, flub requested changes
So I'm taking this back and think this is not a great idea.  The test is great, but making the hyper/http2 transport so generic that it no longer is anything like http2 (no tcp socket) is not.  Testing-wise there is nothing wrong with testing this via a localhost socket.

2022-12-23 13:53 UTC, rklaehn commented
I would agree if we had no need for a non tcp http2 connection other than testing. But we do have the need to support UDS for fabrice / capyloon, and this is an officially supported way to use hyper.

2022-12-28 10:39 UTC, rklaehn commented
Shelved until @flub is back from holiday and we can agree on how to do this and the UDS transport.

2022-12-28 10:39 UTC, closed without merging